version: "3"

services:
  db:
    image: postgres:15-alpine
    container_name: database
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
    volumes:
      - postgres_data_1:/var/lib/postgresql/data
      - ./log:/root/log:cached
    ports:
      - "5432:5432"
    networks:
      - app-network

  # redis:
    # image: redis:alpine
    # container_name: redis
    # restart: on-failure
    # volumes:
      # - redis:/data
    # ports:
      # - "6379:6379"

  migration: &migration
    restart: on-failure:10
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/app
      - rails_cache:/app/tmp/cache
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - assets:/app/public/assets
    networks:
      - app-network

    environment:
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      UN: ${UN}
      PW: ${PW}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    command: bundle exec rake db:create db:migrate

  backend: &backend
    <<: *migration
    depends_on:
      - db
      - migration
    command: bundle exec rails s -b 0.0.0.0 -p 3000
    ports:
      - 3000:3000
    deploy:
      mode: replicated
      replicas: 2

  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    depends_on:
      - backend
    restart: on-failure:3

    ports:
      - 80:80
      - 443:443
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      # - dhparam:/etc/ssl/certs
      - web-root:/var/www/app_name
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: on-failure:3
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/app_name
    depends_on:
      - web
    command: certonly --webroot --webroot-path=/var/www/app_name --email tiendt2311@gmail.com --agree-tos --no-eff-email --force-renewal -d ac.tcyrus.dev
    networks:
      - app-network

  # sidekiq:
    # <<: *backend
    # container_name: hothealth-sidekiq
    # command: bundle exec sidekiq -C config/sidekiq.yml
    # volumes:
      # - sidekiq-logs:/app/log
    # depends_on:
      # - db
      # - redis
      # - migration
    # ports:
      # - 3001:3000


volumes:
  bundle:
  postgres_data_1: {}
  web-root:
  node_modules:
  # redis:
  rails_cache:
  # sidekiq-logs:
  assets:
  certbot-etc:
  certbot-var:
  # dhparam:
    # driver: local
    # driver_opts:
      # type: none
      # device: /home/deploy/dhparam/
      # o: bind

networks:
  app-network:
    driver: bridge
