# fly.toml app configuration file generated for nexus-ac on 2023-09-19T20:30:39+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nexus-ac"
primary_region = "syd"
console_command = "/rails/bin/rails console"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
