name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports: ["5432:5432"]
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_PASSWORD: ""
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
          bundler-cache: true
      - name: Preparing database
        run: bundle exec rake db:setup

      - name: Run tests
        run: bundle exec rspec

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            cd ac_scrapper
            git pull origin main
            export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            export SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }}
            export UN=${{ secrets.UN }}
            export PW=${{ secrets.PW }}
            docker compose down
            docker compose up -d --build
            docker ps

