name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            cd ac_scrapper
            git pull origin main
            export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            export SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }}
            docker compose down
            docker compose up -d --build
            docker ps

